{{- if .Values.memcached.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-{{ include "yopass.fullname" . }}
  labels:
    {{- include "yopass.labels" . | nindent 4 }}
    component: memcached
spec:
  replicas: {{ .Values.memcached.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "yopass.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "yopass.selectorLabels" . | nindent 8 }}
        component: memcached
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "yopass.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.memcached.podSecurityContext | nindent 8 }}
      containers:
        - name: memcached
          args:
            - -m
            - "{{ .Values.memcached.storageMemoryMB | default 16 }}"
          securityContext:
            {{- toYaml .Values.memcached.securityContext | nindent 12 }}
          image: "{{ .Values.memcached.image.repository }}:{{ .Values.memcached.image.tag }}"
          imagePullPolicy: {{ .Values.memcached.image.pullPolicy }}
          ports:
            - name: memcached
              containerPort: {{ .Values.memcached.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.memcached.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}