{{- if .Values.memcached.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: memcached-{{ include "yopass.fullname" . }}
  labels:
    {{- include "yopass.labels" . | nindent 4 }}
    component: memcached
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.memcached.port }}
      targetPort: memcached
      protocol: TCP
      name: memcached
  selector:
    {{- include "yopass.selectorLabels" . | nindent 4 }}
    component: memcached
{{- end }}